### ISSUE TITLE
Segmentation fault in the "medium" self-test on ARM

### ISSUE THREAD

**Issue by tdulcet** [tdulcet/Mlucas#12]
A segmentation fault sometimes occurs in the "medium" self-test: ./Mlucas -s m` on the macOS ARM CI runners:
```
INFO: Maximum recommended exponent for FFT length (3072 Kdbl) = 58884428; p[ = 57984131]/pmax_rec = 0.9847107796.
Initial DWT-multipliers chain length = [short] in carry step.
M57984131: using FFT length 3072K = 3145728 8-byte floats, initial residue shift count = 54682346
This gives an average   18.432658831278484 bits per digit
Using complex FFT radices        48        32        32        32
Using 2 threads in carry step
AddressSanitizer:DEADLYSIGNAL
=================================================================
==11579==ERROR: AddressSanitizer: SEGV on unknown address 0x00015b0d5300 (pc 0x000105d253d0 bp 0x00016b8bcb30 sp 0x00016b8bbf60 T0)
==11579==The signal is caused by a READ memory access.
    #0 0x105d253d0 in radix48_dit_pass1+0x2b2c (Mlucas:arm64+0x1017e53d0)
    #1 0x1047ca600 in mers_mod_square+0xdbb4 (Mlucas:arm64+0x10028a600)
    #2 0x10480a308 in ernstMain+0x60a4 (Mlucas:arm64+0x1002ca308)
    #3 0x10482891c in main+0x41d0 (Mlucas:arm64+0x1002e891c)
    #4 0x188fd50dc  (<unknown module>)

==11579==Register values:
 x[0] = 0x000000016b8bc040   x[1] = 0x000000016b8bbf80   x[2] = 0x000000015b0d5300   x[3] = 0x0000000000202002  
 x[4] = 0x0000000106efa000   x[5] = 0x0000000106efa000   x[6] = 0x0000000106efa000   x[7] = 0x0000000106ef9000  
 x[8] = 0x0000000000000000   x[9] = 0x0000000000000001  x[10] = 0x0000000000000000  x[11] = 0x0000000106efa000  
x[12] = 0x0000007000020000  x[13] = 0x0000000106efa000  x[14] = 0x0000000106f2aa28  x[15] = 0x0000000106efa000  
x[16] = 0x0000000106efa000  x[17] = 0x0000000107ba45e0  x[18] = 0x0000000000000000  x[19] = 0x000000016b8bc300  
x[20] = 0x000000015b0d5300  x[21] = 0x000000010b304880  x[22] = 0x0000000009fba150  x[23] = 0x000000016b8bc060  
x[24] = 0x0000000000000002  x[25] = 0x000000016b8bbfe0  x[26] = 0x000000016b8bbff0  x[27] = 0x000000016b8bbfa0  
x[28] = 0x0000000009f69c50     fp = 0x000000016b8bcb30     lr = 0x0000000106efa000     sp = 0x000000016b8bbf60  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (Mlucas:arm64+0x1017e53d0) in radix48_dit_pass1+0x2b2c
==11579==ABORTING
```

**Comment by MarkRose** [comment]
I tried to reproduce this on aarch64 hardware and could not. Recording the negative result and what I think it does and does not mean.

Tested against current `main` on a Raspberry Pi 4 (Cortex-A72, Debian, gcc 12.2). The native build auto-selects ASIMD, confirmed from the binary's own banner rather than from the build log — `INFO: Build uses ARMv8 advanced-SIMD instruction set`:

| probe | result |
| --- | --- |
| the exact reported case — `-m 57984131 -fft 3072 -iters 100 -radset 48,32,32,32 -cpu 0:1` | clean, exit 0 |
| the same, twelve times, for intermittency | 12/12 clean, identical Res64 |
| the same under `-Og -fsanitize=address` | clean, zero sanitizer diagnostics |
| **full `-s m` under ASan, 2 threads** | **exit 0, 24/24 FFT lengths, zero diagnostics** |

The last row is the one that matters, since a single hand-picked case is much narrower than what you reported: the sweep reached `M57984131` at 3072K with radices 48/32/32/32 — the exact configuration in the traceback — and passed it. About 70 minutes on that hardware.

**I would not call this fixed.** Your report is macOS on Apple Silicon with Apple clang; this is Debian on a Cortex-A72 with gcc. Different microarchitecture, different allocator, different codegen — and an out-of-bounds read only faults when the heap layout puts it somewhere unmapped, which is exactly the kind of thing that differs between those two. Add that the report says "sometimes", and a clean run here is weak evidence either way. Nothing in the PR queue references this issue, so if it *has* been fixed it was incidental and I cannot point at what did it.

## The part I think is actually actionable

While setting this up I found that **no CI job builds hand-tuned SIMD under a sanitizer any more.**

Every sanitizer job is pinned to NOSIMD, because macOS cannot assemble the SIMD under `-Og` (`invalid CFI advance_loc expression`). That pinning is right for macOS, but it retired the one configuration that has ever caught a bug of this class — this issue. A hard SEGV would still fail the plain ARM jobs, since those build native/ASIMD and run `-s m`; but an out-of-bounds *read* that lands in mapped memory, which is what AddressSanitizer reported here, now passes silently everywhere.

Linux does not share the macOS assembler problem. ASIMD plus `-fsanitize=address,undefined` built and ran fine on the aarch64 box above. So the coverage is recoverable on ARM Linux even though it is not on macOS, and #263 adds that job — asserting on the binary's ASIMD banner so it cannot quietly degrade into a duplicate of `ASan-Linux`, and failing on `WARNING: 0 of` as well as on sanitizer output, since per the reasoning on #221 a register clobber corrupts results without ever making a bad memory access. #221 covers the x86 side; the two do not overlap.

My suggestion is to leave this issue open and let #263 answer it on an ongoing basis, rather than closing it on one clean run on hardware that differs from where you saw it. If you still have the macOS runner logs, or it recurs there, I am happy to dig further — a `-s m` ASan sweep on Apple Silicon is the one experiment I cannot run.
